        <div class="row">
            <div class="blog-main">
                    
                   <div class="blog-post">
            <h2 class="blog-post-title">Sample blog post</h2>
            <p class="blog-post-meta"><!-- January 1, 2014 by --> Posted By <a href="#">Mina</a></p>

            <p>This blog post shows a few different types of content that's supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
            
            <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
            <div class="row text-right">
                    <a class="btn btn-warning">Details</a>
                    <a class="btn btn-danger">Delete</a>
            </div>
<hr>

          </div><!-- /.blog-post -->

        </div><!-- /.blog-main --> 


        </div>


        