<section class="container" id="carousel_container">

<?php

?>
   
    <?php

    /*
    for($i=0; $i<count($this->category); $i++){
      echo $this->category[$i]['id'] ." : " . $this->category[$i]['name']."<BR>";
      for($k=0; $k<count($this->subCat); $k++){
        $cat_id=$i+1;
        
        if($this->subCat[$k]['cat_id'] == $cat_id)
        {
          $sum=0;
          for($t=0 ; $t<count($this->thread) ; $t++)
          {
            $subcat_id=$k+1;
            if($this->thread[$t]['cat_id'] == $subcat_id)
            {
              $sum++;
            }
          }

          echo $this->subCat[$k]['name']."  " . $sum ." Topic  " ."<br>";
           
        }

      }
      echo "<hr>";
    }
*/

    for($i=0; $i<count($this->category); $i++){
    ?>
     <div class="row">
        <div class="panel panel-default">
          <div class="panel-heading"><?php echo  $this->category[$i]['name']." ".$this->category[$i]['id'] ?></div>
          <div class="panel-body">
          <?php
            for($k=0; $k<count($this->subCat); $k++){
              $cat_id=$i+1;
              
              if($this->subCat[$k]['cat_id'] == $cat_id)
              {
                $sum=0;
                for($t=1 ; $t<count($this->thread) ; $t++)
                {
                  $subcat_id=$k+1;
                  if($this->thread[$t]['cat_id'] == $subcat_id)
                  {
                    $sum++;
                  }
                }

          ?>
              <div class="row"><div class="span7 glyphicon glyphicon-plus"><a href="<?php echo $this->baseUrl() ?>/subcats/view/id/<?php echo $this->subCat[$k]['id'] ?>"> <?php echo $this->subCat[$k]['name']; ?></a></div><div class="span4"> <?php echo $sum ?>Topics</div>  </div><hr>
              
              <?php
            }
          }
              ?>
          </div>
        </div>
    </div>
    <?php
  }
    ?>
    
  </section>


        