<section class="container" id="carousel_container">

	<div class="page-header text-center">
  		<h3  style="text-shadow:0px 0px 5px #555;">View User</h3>
  	</div>
    <label class=" col-sm-12 control-label"><h1  > <small>All User's Information:</small></h1></label>
     <div class="row">
        <form action="#" method="post" role="form">
            <article class="span6">
                <label for="author">Name:</label> <input name="author" type="text" disabled value="Mina Amir Samy" class="input_field input-xxlarge" id="author" maxlength="40" />
                    <div class="cleaner"></div>
                    <label for="email">Email:</label> <input name="email" disabled type="text" class="input_field input-xxlarge" id="email" value="eng.mina23@gmail.com" maxlength="40" />
                    <div class="cleaner"></div>
                    <label for="phone">Last Login Date:</label> <input name="phone" type="text" value="13 / Dec / 2013" disabled class="input_field input-xxlarge" id="phone" maxlength="20" />
                    <div class="cleaner"></div>
              </article>
              <article class="span6">
              
                <label for="author"> Date Of Birth:</label> <input name="author" disabled type="text" class="input_field input-xxlarge" id="author" maxlength="40" />
                    <div class="cleaner"></div>
                    
              </article>
          </form>
     </div>
     <label class=" col-sm-12 control-label"><h1  > <small>All User's Topics :</small></h1></label>
     <div class="row">
     		<table class="table table-bordered  table-hover table-responsive ">
                            <thead>
                                <tr class="active ">
                                    <th width="5%">#</th>
                                    <th width="50%"> Title</th>
                                    <th>Category</th>
                                </tr>
                              </thead>
                              <tbody>
                              
                              
                              			<tr>
                                            <td>1</td>
                                            <td>How it will Work</td>
                                             <td>News</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>How it will Work</td>
                                             <td>Ask Expert</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>How it will Work</td>
                                             <td>News</td>
                                        </tr>
                                        <tr>
                                            <td>4</td>
                                            <td>How it will Work</td>
                                             <td>Medical Descussion</td>
                                        </tr>
                                        <tr>
                                            <td>5</td>
                                            <td>How it will Work</td>
                                             <td>News</td>
                                        </tr>
                                
                            	</tbody>
                            </table>
     </div>

</section>