<section class="container" id="carousel_container">


<div class="page-header text-center">
  <h3 >All Users</h3>
</div>

<!-- Quiz Table -->

  <div class="row ">
        <a href="<?php echo $this->baseUrl(); ?>/admin/adduser" class="btn btn-info btn-block " > Insert New User </a>
    </div>
    <div class="row mytable "  id="books_cat">
      
        <table class="table table-bordered  table-hover table-responsive ">
            <thead>
                <tr class="active ">
                    <th width="5%">#</th>
                    <th width="50%"> Name</th>
                    <th>Type</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody >
                <?php
                    if($this->data){
                         for($i=0; $i<count($this->data); $i++){
                               ?>
                                <tr>
                                    <td><?php echo $this -> data[$i]['id'] ?></td>
                                    <td><?php echo $this -> data[$i]['name'] ?></td>
                                    <td><?php if($this -> data[$i]['type'] == '1') echo 'admin'; else echo 'User'; ?></td>
                                    <td class=""> 
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/viewuser/id/<?php echo $this ->data[$i]['id'] ?>" target="_blank" class="btn btn-info btn-sm">View</a>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/edituser/id/<?php echo $this ->data[$i]['id'] ?>" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                        <?php if($this -> data[$i]['is_blocked'] == '1'){?>
                                                <a href="<?php echo $this->baseUrl(); ?>/admin/unblockuser/id/<?php echo $this ->data[$i]['id'] ?>"  class="btn btn-info btn-sm">Unblock</a>

                                           <?php }else { ?>
                                                <a href="<?php echo $this->baseUrl(); ?>/admin/blockuser/id/<?php echo $this ->data[$i]['id'] ?>"  class="btn btn-info btn-sm">Block</a>
                                            <?php } ?>

                                            <?php if($this -> data[$i]['type'] == '1'){?>
                                                <a href="<?php echo $this->baseUrl(); ?>/admin/setuser/id/<?php echo $this ->data[$i]['id'] ?>"  class="btn btn-info btn-sm">User</a>

                                           <?php }else { ?>
                                                <a href="<?php echo $this->baseUrl(); ?>/admin/setadmin/id/<?php echo $this ->data[$i]['id'] ?>"  class="btn btn-info btn-sm">Admin</a>
                                            <?php } ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/admin/deleteuser/id/<?php echo $this ->data[$i]['id'] ?>" target="_blank" class="btn btn-info btn-sm">Delete</a>
                                    </td>
                                </tr>
                               <?php
                           } 
                    }
                ?>    

                
                
            </tbody>
        </table>
        
    </div>
        
   
</section>


        