<section class="container" id="carousel_container">

	<div class="page-header text-center">
  		<h3 >All News</h3>
  	</div>
    
    <div class="text-right">
    	<a href="<?php echo $this -> baseUrl(); ?>/subcats/add" class="btn btn-info ">Insert News</a>
    </div>
    <div class="row">
    	
        <section id="content">
            <article class="post_box"> <a href="<?php echo $this -> baseUrl(); ?>/subcats/view"><img src="images/templatemo_image_01.png" alt="Model Girl 1" class="image_frame_300 img-polaroid"/></a>
              <h2>Proin Mauris Nibh Aliquet id Consequat</h2>
              <p> In ante felis, molestie eu euismod id, gravida id enim. Nam consequat vehicula libero, in dignissim velit blandit vel. Morbi quam sapien, pellentesque id aliquam eu, molestie non velit, non viverra quam sem eget elit.</p>
              <a href="<?php echo $this -> baseUrl(); ?>/subcats/view" class="btn btn-danger">Read more...</a>
              <div class="cleaner"></div>
              <div class="text-right">
              	<a href="<?php echo $this -> baseUrl(); ?>/subcats/edit" target="_blank" class="btn btn-info ">Edit News</a>
                <a href="<?php echo $this -> baseUrl(); ?>/subcats/delete" target="_blank" class="btn btn-info ">Delete News</a>
              </div>
              
              <div class="post_meta">
                Posted: <i>24 May 2072</i> 
                <span>( 256 comments )</span>
              </div>
    
            </article>
            <article class="post_box">
              <h2>News Without Image</h2>
              <p>Suspendisse bibendum eros eu lorem pharetra porta. Suspendisse porta convallis libero eu ultricies. Aenean dictum lacus vitae dolor commodo fringilla. Donec vitae justo sed diam tincidunt gravida sed vel nisi.</p>
              <a href="<?php echo $this -> baseUrl(); ?>/subcats/view" class="btn btn-danger">Read more...</a>
              <div class="cleaner"></div>
              <div class="text-right">
              	<a href="<?php echo $this -> baseUrl(); ?>/subcats/edit" target="_blank" class="btn btn-info ">Edit News</a>
                <a href="<?php echo $this -> baseUrl(); ?>/subcats/delete" target="_blank" class="btn btn-info ">Delete News</a>
              </div>
              <div class="post_meta">
                Posted: <i>20 May 2072</i>
                <span>( 512 comments )</span>
              </div>
    
            </article>
            
            <article class="post_box"> <a href="<?php echo $this -> baseUrl(); ?>/subcats/view"><img src="images/templatemo_image_03.png" alt="Model Girl 3" class="image_frame_300 img-polaroid" /></a>
              <h2>Nullam Bibendum Lacinia Venenatis</h2>
              <p>Nullam bibendum lacinia venenatis. Phasellus sapien nisl, scelerisque eu sodales sit amet, imperdiet non neque. Curabitur viverra cursus augue, sed mattis nulla dignissim et.</p>
              <a href="view.php" class="btn btn-danger">Read more...</a>
              <div class="cleaner"></div>
              <div class="text-right">
              	<a href="<?php echo $this -> baseUrl(); ?>/subcats/edit" target="_blank" class="btn btn-info ">Edit News</a>
                <a href="<?php echo $this -> baseUrl(); ?>/subcats/delete" target="_blank" class="btn btn-info ">Delete News</a>
              </div>
              <div class="post_meta">
                Posted: <i>16 May 2072</i> 
                <span>( 768 comments )</span>
              </div>
    
            </article>
            
            
            <nav class="pagination pagination-centered">
              <ul>
                <li class="disabled"><a href="http://www.templatemo.com" target="_parent">&laquo;</a></li>
                <li class="active"><a href="http://www.templatemo.com/page/1" target="_parent">1</a></li>
                <li><a href="http://www.templatemo.com/page/2" target="_parent">2</a></li>
                <li><a href="http://www.templatemo.com/page/3" target="_parent">3</a></li>
                <li><a href="http://www.templatemo.com/page/4" target="_parent">4</a></li>
                <li><a href="http://www.templatemo.com/page/5" target="_parent">5</a></li>
                <li><a href="http://www.templatemo.com/page/6" target="_parent">6</a></li>
                <li><a href="http://www.templatemo.com/page/7" target="_parent">&raquo;</a></li>
              </ul>
            </nav> 
            
        </section>
    </div>
        
   
</section>


        