<section class="container" id="carousel_container">


<div class="page-header text-center">
                                  <h3 >All Users</h3>
                                </div>
                                
                                <!-- Quiz Table -->
                                
                                <div class="row text-center ">
                                  
                      <input class="form-control  input-block-level text-center" type="text" placeholder="Search By  User Name ">
                                </div>
                                  <div class="row ">
                                        <a href="<?php echo $this->baseUrl(); ?>/users/add" class="btn btn-info btn-block " > Insert New User </a>
                                    </div>
                                    <div class="row mytable "  id="books_cat">
                                      
                                        <table class="table table-bordered  table-hover table-responsive ">
                                            <thead>
                                                <tr class="active ">
                                                    <th width="5%">#</th>
                                                    <th width="50%"> Name</th>
                                                    <th>Type</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody >
                                                <tr>
                                                    <td>1</td>
                                                    <td>Dr. Ahmed </td>
                                                    <td>Admin</td>
                                                    <td class=""> 
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/view" target="_blank" class="btn btn-info btn-sm">View</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/edit" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/delete" target="_blank" class="btn btn-info btn-sm">Delete</a>
                                                    </td>
                                                </tr>
                                                
                                                <tr>
                                                    <td>2</td>
                                                    <td>Dr. Mina </td>
                                                    <td>Sub-Admin</td>
                                                    <td class=""> 
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/view" target="_blank" class="btn btn-info btn-sm">View</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/edit" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/delete" target="_blank" class="btn btn-info btn-sm">Delete</a>
                                                    </td>
                                                </tr>
                                                
                                                <tr>
                                                    <td>3</td>
                                                    <td>Dr. Mohamed </td>
                                                    <td>User</td>
                                                    <td class=""> 
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/view" target="_blank" class="btn btn-info btn-sm">View</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/edit" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/delete" target="_blank" class="btn btn-info btn-sm">Delete</a>
                                                    </td>
                                                </tr>
                                                
                                                <tr>
                                                    <td>4</td>
                                                    <td>Dr. Saad </td>
                                                    <td>Blocked</td>
                                                    <td class=""> 
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/view" target="_blank" class="btn btn-info btn-sm">View</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/edit" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                                        <a href="<?php echo $this->baseUrl(); ?>/users/delete" target="_blank" class="btn btn-info btn-sm">Delete</a>
                                                    </td>
                                                </tr>
                                                
                                            </tbody>
                                        </table>
                                        
                                    </div>
        
   
</section>


        