<?php echo $this->doctype() ?>
<html>
	<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>


	</head>
	<body>
  <?php $auth = Zend_Auth::getInstance();
    if($auth -> hasIdentity()){
        $userObj = $auth->getIdentity();
      echo $userObj ->type;
    }
     ?>
		<header>
    <div class="navbar navbar-inverse navbar-fixed-top">
      
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">DMS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<?php echo $this ->baseUrl(); ?>/">Home</a></li>
        
        <?php

  //On every init() of controlleryou have to check is authenticated or not
        $authorization = Zend_Auth::getInstance();
        if(!$authorization -> hasIdentity()) {
        ?>
        <li ><a href="<?php echo $this ->baseUrl(); ?>/users/login">Login </a></li>
        <li ><a href="<?php echo $this ->baseUrl(); ?>/users/add">Register </a></li>
        <?php
        }
        else
        {
            ?>
            <li ><a href="<?php echo $this ->baseUrl(); ?>/users/edit">Setting </a></li>
          <?php


            // Check if user is Admin
            $userObj = $authorization->getIdentity();
            if($userObj->type == '1'){
               ?>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">AdminPanel <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="<?php echo $this ->baseUrl(); ?>/admin/">Users</a></li>
                    <li><a href="<?php echo $this ->baseUrl(); ?>/admin/cats">Categories</a></li>
                    <li><a href="<?php echo $this ->baseUrl(); ?>/admin/subcats">Sub Categories</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="<?php echo $this ->baseUrl(); ?>/admin/site">Site Setting</a></li>
                    
                  </ul>
                </li>
               <?php    
            }
            else{
               // $this->redirect('/');       
            }
         }
  ?>
        
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <?php
      if($authorization -> hasIdentity()) {
      ?>
        <li><a href="<?php echo $this ->baseUrl(); ?>/users/logout">logout</a></li>
      <?php
    }
      ?>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->




    </div>
  </header>	


<?php echo $this->layout()->content; ?>
	
	

	
	 <footer>
    <div class="container">        
      <div id= "latest" class="row">
        <section class="span4 rp_box_wrapper">
          <h4>Latest News Posts<i class="icon-pencil icon-white"></i></h4>
          <article class="rp_box">
            <a href="#"><img src="<?php echo $this -> baseUrl(); ?>/images/templatemo_image_04.png" alt="image 4" class="img-rounded"/></a>
            <div class="date">May 24, 2072</div>
            <a href="#">Sed quam lorem, ultricies et lobortis rutrum, tristique id lorem.</a>            
          </article> 
          <article class="rp_box">
            <a href="#"><img src="<?php echo $this -> baseUrl(); ?>/images/templatemo_image_05.png" alt="image 5"  class="img-rounded"/></a>
            <div class="date">May 20, 2072</div>
            <a href="#">Duis vestibul<?php echo $this -> baseUrl(); ?>/um libero accumsan lorem varius tristique.</a>            
          </article> 
          <article class="rp_box">
            <a href="#"><img src="<?php echo $this -> baseUrl(); ?>/images/templatemo_image_06.png" alt="image 6"  class="img-rounded"/></a>
            <div class="date">May 16, 2072</div>
            <a href="#">Class aptent taciti sociosqu ad litora torquent per conubia.</a>            
          </article>
          <p><a class="btn btn-default pull-right"  href="#">See All News &raquo;</a></p>
        </section>
        
        <section class="span4 rp_box_wrapper">
        
          <h4>Latest Posts</h4>
          <article class="rp_box">
            <a href="#"><img src="<?php echo $this -> baseUrl(); ?>/images/templatemo_image_04.png" alt="image 4" class="img-rounded"/></a>
            <div class="date">May 24, 2072</div>
            <a href="#">Sed quam lorem, ultricies et lobortis rutrum, tristique id lorem.</a>            
          </article> 
          <article class="rp_box">
            <a href="#"><img src="<?php echo $this -> baseUrl(); ?>/images/templatemo_image_05.png" alt="image 5"  class="img-rounded"/></a>
            <div class="date">May 20, 2072</div>
            <a href="#">Duis vestibulum libero accumsan lorem varius tristique.</a>            
          </article> 
          <article class="rp_box">
            <a href="#"><img src="<?php echo $this -> baseUrl(); ?>/images/templatemo_image_06.png" alt="image 6"  class="img-rounded"/></a>
            <div class="date">May 16, 2072</div>
            <a href="#">Class aptent taciti sociosqu ad litora torquent per conubia.</a>            
          </article>
       </section>
       
       <section class="span3 rp_box_wrapper">
       
        <h4>Contact Us <i class="icon-envelope icon-white"></i></h4>
        <form>
          <input name="fullname" type="text" id="fullname" placeholder="Name" maxlength="30" />
          <input name="email" type="text" id="email" placeholder="Email" maxlength="30" />
          <textarea rows="3" placeholder="Message"></textarea>
          <p><button type="submit" class="btn">Submit</button></p>
        </form>
        
        <address>
          <strong>Responsive</strong><br>
          222-444 Aliquam semper dignissim,<br>
      	  Fusce cursus turpis lacus, 22440<br>
          Sit amet tortor<br />
          <a href="http://tr.vectorhq.com/"   class="res_about" >http://tr.vectorhq.com</a><br>
          <abbr title="Phone">Phone:</abbr> <a href="tel:020-040-0240" title="give us a call">020-040-0240</a><br>
          <abbr title="Email">Email:</abbr> <a href="mailto:info@company.com">info@company.com</a>
        </address> 

      </section>
      
    </div>
      <div class="credit">
        <p id="templatemo_cr_bar">
          Copyright © 2072 <a href="#">Your Company Name</a> | <a href="http://www.templatemo.com/preview/templatemo_374_responsive">Responsive</a> by <a href="http://www.templatemo.com">templatemo</a>
        </p>
      </div>
    </div>
  </footer>

<?php echo $this->headScript() ?>
<script>

            CKEDITOR.replace( 'editor1', {
                fullPage: true,
                uiColor: '#ffdd00',
                allowedContent: true,
                extraPlugins: 'wysiwygarea'
            });
        </script>
  
  </body>
</html>