<section class="container" id="carousel_container">

	<div class="page-header text-center">
            <h3 >Scientific Activities</h3>
          </div>
          
          <!-- Quiz Table -->
          
          <div class="row text-center ">
            
<input class="form-control  input-block-level text-center" type="text" placeholder="Search By  User Name ">
          </div>
            <div class="row ">
                  <a href="insert.php" class="btn btn-info btn-block " > Insert New Activity </a>
              </div>
              <div class="row mytable "  id="books_cat">
                
                  <table class="table table-bordered  table-hover table-responsive ">
                      <thead>
                          <tr class="active ">
                              <th width="5%">#</th>
                              <th width="50%"> Title</th>
                              <th>no Of Comments</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody >
                          <tr>
                              <td>1</td>
                              <td>Mab 2014 </td>
                              <td>5</td>
                              <td class=""> 
                                  <a href="view.php" target="_blank" class="btn btn-info btn-sm">View</a>
                                  <a href="edit.php" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                  <a href="delete.php" target="_blank" class="btn btn-info btn-sm">Delete</a>
                              </td>
                          </tr>
                          
                         
                          
                          <tr>
                              <td>2</td>
                              <td>Mab 2013 </td>
                              <td>5</td>
                              <td class=""> 
                                  <a href="view.php" target="_blank" class="btn btn-info btn-sm">View</a>
                                  <a href="edit.php" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                  <a href="delete.php" target="_blank" class="btn btn-info btn-sm">Delete</a>
                              </td>
                          </tr>
                          
                          <tr>
                              <td>3</td>
                              <td>Mab 2012 </td>
                              <td>5</td>
                              <td class=""> 
                                  <a href="view.php" target="_blank" class="btn btn-info btn-sm">View</a>
                                  <a href="edit.php" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                  <a href="delete.php" target="_blank" class="btn btn-info btn-sm">Delete</a>
                              </td>
                          </tr>
                          
                          <tr>
                              <td>4</td>
                              <td>Mab 2011 </td>
                              <td>2</td>
                              <td class=""> 
                                  <a href="view.php" target="_blank" class="btn btn-info btn-sm">View</a>
                                  <a href="edit.php" target="_blank" class="btn btn-info btn-sm">Edit</a>
                                  <a href="delete.php" target="_blank" class="btn btn-info btn-sm">Delete</a>
                              </td>
                          </tr>
                          
                      </tbody>
                  </table>
                  
              </div>
   
</section>


        