<section class="container" id="carousel_container">

    <div class="page-header text-center">
        <h3  style="text-shadow:0px 0px 5px #555;">Delete Thread</h3>
    </div>
    <div class="row text-center">
        Are you Sure you Want To Delete This Thread ?!
    </div>

    <div class="row text-center">
        <form action="delete.php" method="post">
            <input  class="btn btn-danger" type="submit" value="Yes" name="delete_btn" />
            <a href="delete.php" class="btn btn-success">No</a>
        </form>
    </div>

</section>